server:
  port: 8086
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localHost:5432/BRDS
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
excel:
  contentType: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet